### ISSUE TITLE
COMMENTING/POLISHING CODE

### ISSUE THREAD

**Issue by jonbrunt** [jonbrunt/ai-portfolio#21]
## CODE REVIEW

After the frontend is complete, we need to pass through all files and comment them better, and look for details like explicit types (TS) that are missing, etc. The details that have been already found are minor, but worth a quick look while sensible commenting is added beyond what already exists.

## Expected Behavior

All code should be commented and complete

## Actual Behavior

While not a major issue, comments and details are lacking, but this is ok for an MVP of the product. Needs to be improved before release

## Tasks
- [ ] Check git stash for stashed changes
- [ ] Comment all code in the codebase (reasonable, short comments where justified)
- [ ] Review the code for missing or excessive/unnecessary syntax 

## Tags
\#enhancement

**Comment by jonbrunt** [comment]
A code review is needed. The review should include adding comments, refactoring, and standardizing code (minor changes).  First, we will finish the testing, deployment, and CI/CD pipelines, but the priority of this Issue has gone from low to medium, at this point.
